on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: azure/docker-login@v1
      with:
        login-server: mmondocker.azurecr.io
        username: ${{ secrets.acr_mmondocker_username }}
        password: ${{ secrets.acr_mmondocker_password }}
    
    - name: Build
      run: |
          cd "./src"
          dotnet restore
          dotnet build
    - name: test
      run: |
          docker-compose -f ./.github/tests/docker-compose-test.yml up
